# .npmrc の save-exact=true を再現
defaultSemverRangePrefix: ''

# pnp を利用せず、 `node_modules` に保存する
nodeLinker: node-modules

# global なディレクトリに install し project local には hard link を行う
nmMode: hardlinks-global
